### PR TITLE
Youtube: allows urls without www and adds youtu.be support. Fixes #2605522

### PR DESCRIPTION
**Pull request by axe312ger**
I tested the regular expressions with this set of possible youtube urls and they match very well:

```
https://youtube.com/v/qT8YT-e3QBk&index=3&list=WL
http://youtube.com/v/qT8YT-e3QBk&index=3&list=WL
https://www.youtube.com/v/qT8YT-e3QBk&index=3&list=WL
http://www.youtube.com/v/qT8YT-e3QBk&index=3&list=WL
https://www.youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
http://www.youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
https://www.youtube.com/watch?v=qT8YT-e3QBk
http://www.youtube.com/watch?v=qT8YT-e3QBk
https://youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
http://youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
https://youtube.com/watch?v=qT8YT-e3QBk
http://youtube.com/watch?v=qT8YT-e3QBk
http://youtu.be/qT8YT-e3QBk
https://youtu.be/qT8YT-e3QBk

//youtube.com/v/qT8YT-e3QBk&index=3&list=WL
//www.youtube.com/v/qT8YT-e3QBk&index=3&list=WL
//www.youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
//www.youtube.com/watch?v=qT8YT-e3QBk
//youtube.com/watch?v=qT8YT-e3QBk&index=3&list=WL
//youtube.com/watch?v=qT8YT-e3QBk
//youtu.be/qT8YT-e3QBk

<iframe width="560" height="315" src="https://www.youtube.com/embed/qT8YT-e3QBk" frameborder="0" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://youtube.com/embed/qT8YT-e3QBk" frameborder="0" allowfullscreen></iframe>
<iframe width="560" height="315" src="//www.youtube.com/embed/qT8YT-e3QBk" frameborder="0" allowfullscreen></iframe>
<iframe width="560" height="315" src="//youtube.com/embed/qT8YT-e3QBk" frameborder="0" allowfullscreen></iframe>
```

### CODE REVIEW

**Comment by yannickoo** [comment]
:heart:

**Comment by axe312ger** [comment]
Drupal.org issue: https://www.drupal.org/node/2605522

**Comment by slashrsm** [comment]
Merged. Also added your test urls/embed codes to the relevant test class. 

https://github.com/drupal-media/media_entity_embeddable_video/commit/38615212aa4ea54f407a72e7b887670a8f5f0364

**Comment by axe312ger** [comment]
Awesome. Thanks!

**Pull request merged**
